# Generated by Django 5.0.3 on 2024-05-08 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=63, verbose_name='Display name')),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
            ],
        ),
    ]
