# Generated by Django 5.0.2 on 2024-05-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_articleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
