# Generated by Django 5.0.2 on 2024-05-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('SA', 'On Sale'), ('OOS', 'Out of Stock')], default='AV', max_length=50)),
            ],
            options={
                'ordering': ['name', 'status'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OC', 'On Cart'), ('TP', 'To Pay'), ('TS', 'To Ship'), ('TR', 'To Receive'), ('D', 'Delivered')], default='OC', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
