# Generated by Django 3.0.4 on 2024-05-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_product_owner_product_status_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'status']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['status']},
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(0, 'Available'), (1, 'On Sale'), (2, 'Out of Stock')], default=(0, 'Available'), max_length=50),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[(0, 'On Cart'), (1, 'To Pay'), (2, 'To Ship'), (3, 'To Receive'), (4, 'Delivered')], max_length=50),
        ),
    ]
