# Generated by Django 5.0.6 on 2024-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0004_alter_product_id_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('SA', 'On Sale'), ('OOS', 'Out of Stock')], default='AV', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('OC', 'On Cart'), ('TP', 'To Pay'), ('TS', 'To Ship'), ('TR', 'To Receive'), ('D', 'Delivered')], default='OC', max_length=20),
        ),
    ]
